### ISSUE TITLE
Dev lab07 - 3scale automation script

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#173]
**Two things**

1) the Automate script failed at

```curl -X POST http://threescale-automate-international.dil.opentry.me/threescale/automate/<access_token>/user11/dil.opentry.me
org.apache.camel.http.common.HttpOperationFailedException: HTTP operation failed invoking https://user11-admin.dil.opentry.me/admin/api/services/218/metrics.xml?access_token=<access_token> with statusCode: 404
	at org.apache.camel.component.http4.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:312)
	at org.apache.camel.component.http4.HttpProducer.process(HttpProducer.java:207)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendDynamicProcessor$1.doInAsyncProducer(SendDynamicProcessor.java:132)
	at org.apache.camel.impl.ProducerCache.doInAsyncProducer(ProducerCache.java:445)
	at org.apache.camel.processor.SendDynamicProcessor.process(SendDynamicProcessor.java:127)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
```

2) Mapping rule `/locations` is not created as part of the automation script

**Comment by VinayBhalerao** [comment]
The default service created is `API` which has the authentication mode as `user_key`. Since the tutorial is based on `open-id` connect, we should also modify the authentication mode to `open_id` connect

![integrations_-_show___red_hat_3scale_api_management](https://user-images.githubusercontent.com/7827135/47752567-0f7bca00-dc52-11e8-9566-1be4e2f3899b.png)

**Comment by VinayBhalerao** [comment]
In citizen lab, step 3.7, we do it here https://github.com/RedHatWorkshops/dayinthelife-integration/tree/master/docs/labs/citizen-integrator-track/lab05#step-3-configure-3scale-integration

1) Great if we can add that as part of automation OR
2) If it's tricky, we can then add manual step to enable `open_id`

**Comment by weimeilin79** [comment]
Sorry, I accidentally push my testing hardcoded route into the repo. I test it again dil1 with a new user id. Now it should work. 
<img width="1591" alt="screen shot 2018-10-30 at 7 53 11 pm" src="https://user-images.githubusercontent.com/2534483/47757690-ef620000-dc7d-11e8-91f2-ba40a82f26ad.png">

And also updated the backend_version. 
<img width="1480" alt="screen shot 2018-10-30 at 7 52 11 pm" src="https://user-images.githubusercontent.com/2534483/47757714-03a5fd00-dc7e-11e8-8097-d985976a41c4.png">

**Comment by VinayBhalerao** [comment]
Works as expected. Closing.
